name: weather
description: "A Flutter weather application using OpenWeatherMap API."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Networking
  dio: ^5.7.0

  # Data Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Utils
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  timeago: ^3.7.1
  collection: ^1.19.1

  # Storage
  shared_preferences: ^2.2.2

  # Environment Variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3

  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/icons/sun.png"
  image_path: "assets/icons/sun.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color: "#FFFFFF"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/sun.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - .env

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
